config/routes.rb
Rails.application.routes.draw do

  resources :blogs 
  resources :product_features do
    collection do 
      get "product_index"
    end
  end
  resources :product_photos
  resources :molpay_transaction_histories do
    collection do 
      post "molpay"
    end
  end

  resources :receipts
  
  resources :email_settings
  
  resources :regions
  
  resources :sources_types
  
  resources :product_settings
  
  resources :reservations do
    member do
      get "buyer"
    end
    collection do
      post "create_lot"
      get "confirm_reservation"
    end
  end

  resources :reports do
    member do
      get "menu"
      get "summary_report"
      get "analysis_age_report"
      get "analysis_unit_report"
      get "analysis_sources_type_report"
      get "analysis_region_report"
      get "analysis_race_report"
      get "sales"
      get "monthly_sales"
      get "agency_sales"
      get "cancellation"
      get "rejection"
      get "export_summary_report_excel"
      get "export_analysis_unit_excel"
      get "export_analysis_age_race_excel"
      get "export_sources_type_excel"
      get "export_regions_excel"
      get "sales_excel"
      get "monthly_excel"
    end
  end
  
  resources :buyers
  resources :company_settings 

  resources :sales do
    member do
      post "confirm"
      post "reject"
      post "cancel"
      get "new_payment"
      post "add_payment"
    end
    collection do
      get "export_purchaser_excel"
    end
  end

  devise_for :admins, :controllers => { :sessions => "super_admin/sessions", :registrations => "super_admin/registrations"  } # :skip => :registrations,
  devise_for :users, :controllers => { :registrations => :registrations, :sessions => :sessions, :passwords => :passwords  }

  resources :users do
    collection do
      post "create_member"
      post "create_user_access"
    end
    member do
      delete "remove_customize"
      patch  "update_member"
      delete "suspend"
      get    "activate"
    end
  end

  resources :lots do 
    member do
      post "bulk_update"
    end
  end

  resources :product_types do 
    member do 
      post "bulk_update"
    end
  end

  resources :products do 
    collection do
      post "create_lot"
      get "published"
    end
    member do
      post "update_email_setting"
      post "update_setting"
      post "update_region"
      post "update_sources_type"
      post "update_reservation_customization"
      get "site_plans"
      get "floor_plans"
    end
    resources :site_plans
    resources :floor_plans
    resources :enquiries, only: [:create, :index, :show]
  end

  resources :phases do 
    collection do 
      post "update_product"
    end
  end

  resources :projects do
    collection do
      post "update_project"
      post "update_phase"
    end
  end

  mount RailsEmailPreview::Engine, at: 'emails'

  resources :companies do
    member do
      post "update_setting"
      patch "update_profile"
    end
    collection do
      get "profile"
    end
  end

  namespace :super_admin do
    resources :admins
    resources :companies do
      member do
        post "update_setting"
      end
    end
  end

  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  match 'molpay/subscribe' => "molpay#subscribe", via: [:post, :get]
  match 'molpay/create_molpay_transaction' => "molpay#create_molpay_transaction", via: [:post, :get]
  match 'molpay/return_url' => "molpay#return_url", via: [:post, :get]
  match 'molpay/molpay' => "molpay#molpay", via: [:get, :post]
  
  get 'home' => "pages#home"
  get 'team' => "pages#team"
  get 'service' => "pages#service"
  get 'contact' => "pages#contact"
  get 'about_us' => "pages#about_us"
  get 'listings' => "pages#listings"
  get 'listing_details' => "pages#listing_details"
  get 'blog' => "pages#blog"
  get 'blog_details' => "pages#blog_details"
  match 'pages/sign_up_email' => "pages#sign_up_email", via: [:get, :post]
  match 'pages/personal_detail_email' => "pages#personal_detail_email", via: [:get, :post]

  get 'supermin_board' => 'super_admin/dashboard#index', as: :supermin_board
  
  root 'dashboard#index'
  

end

app/controllers/super_admin/admins_controller.rb
class SuperAdmin::AdminsController < ApplicationController
  before_action :authenticate_super_admin!
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admins }
    end
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin }
    end
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to super_admin_admin_path(@admin), notice: 'Admin was successfully created.' }
        format.json { render json: @admin, status: :created }
      else
        format.html { 
          flash.now[:alert] =  @admin.errors.full_messages.join("<br>")
          render action: 'new' }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to super_admin_admin_path(@admin), notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { 
          flash.now[:alert] =  @admin.errors.full_messages.join("<br>")
          render action: 'edit' }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to super_admin_admins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:display_name, :email, :username, :password, :password_confirmation)
    end
end

app/controllers/super_admin/companies_controller.rb
class SuperAdmin::CompaniesController < ApplicationController
  before_action :authenticate_super_admin!
  before_action :set_company, only: [:show, :edit, :update, :destroy, :update_setting]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
    @user = User.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create

    @company = Company.new(company_params)
    @company.type_id = params[:company_type_id]

    @user = User.new(email: params[:company_email], password: params[:company_password], password_confirmation: params[:company_password_confirmation], display_name: "Admin", username: params[:company_username])
    @user.type_id = User::ADMIN
      if @company.valid? && @user.valid?
        if @company.save
          @user.company_id = @company.id
          @user.save!
          redirect_to super_admin_company_path(@company), notice: 'Company was successfully created.'
        else
          flash.now[:alert] =  @company.errors.full_messages.join("<br>")
          render action: 'new'
        end
      else
        msg = ""
        msg << @company.errors.full_messages.join("<br>") if @company.errors.any?
        msg << @user.errors.full_messages.join("<br>") if @user.errors.any?
        flash.now[:alert] = msg
        render action: 'new'
      end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @company.type_id = params[:company_type_id]
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to super_admin_company_path(@company), notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to super_admin_companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :registration_number, :address, :phone_number, :fax_number, :type_id, :parent_id,:slug, :username)
    end

end

app/controllers/super_admin/dashboard_controller.rb
class SuperAdmin::DashboardController < ApplicationController
  before_action :authenticate_super_admin!
  
  def index
  end
end

app/controllers/super_admin/registrations_controller.rb
class SuperAdmin::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, if: :devise_controller?
  layout "application"

	def new
		# @company = Company.new
    # self.resource = User.new
    # raise ActiveRecord::RecordNotFound
    raise ActionController::RoutingError.new('Not Found')
  end

  def create
  	# render :text => params
    # user = User.new(sign_up_params)
		# @company = Company.new(company_params)
		# @company.type_id = params[:type_id]

		# self.resource = user
		# if @company.save
		# 	user.company_id = @company.id
		# 	if user.save 
		# 		sign_up(resource_name, resource)
		# 		redirect_to root_url, notice: "Successfully sign up."
		# 	else
		# 		logger.info {resource.errors.full_messages}
		# 		flash[:alert] = "#{resource.errors.full_messages}"
		# 		render :action => "new"
		# 	end
		# else
		# 	flash[:alert] = "Errors.."
		# 	render :action => "new"
		# end
    raise ActionController::RoutingError.new('Not Found')
  end

  def edit
    self.resource = current_admin
    # raise ActionController::RoutingError.new('Not Found')
  end

  private

  def after_update_path_for(resource)
    edit_admin_registration_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:username, :email, :display_name, :contact_number, :password, :password_confirmation, :current_password)
    end
  end

end

app/controllers/super_admin/sessions_controller.rb
class SuperAdmin::SessionsController < Devise::SessionsController
	prepend_before_action :require_no_authentication, only: [ :new, :create ]
	before_action :configure_permitted_parameters
  # skip_before_action :verify_authenticity_token
  layout "devise"

  def create
  	#render :text => sign_in_params
    super do |resource|
      # do some other job

    end
  end

  def destroy
    super do |resource|
      # do some other job
    end
  end

  protected

  def after_sign_in_path_for(admin)
    supermin_board_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(:email, :password)
    end
  end

end

app/views/super_admin/admins/_form.html.erb
<% if @admin.new_record? %>
  <% posting_path = super_admin_admins_path %>
<% else %>
  <% posting_path = super_admin_admin_path(@admin) %>
<% end %>
<%= form_for(@admin, url: posting_path, html: {class: "panel-body form-horizontal form-padding"}) do |f| %>

   <div class="form-group">
    <label class="col-md-3 control-label" for="admin_display_name">Full Name</label>
    <div class="col-md-9">
      <input type="text" id="admin_username" name="admin[username]" class="form-control" placeholder="Full name" value="<%= @admin.username %>">
      <!-- <small class="help-block">This is a help text</small> -->
    </div>
  </div>

 <div class="form-group">
    <label class="col-md-3 control-label" for="admin_display_name">Display Name</label>
    <div class="col-md-9">
      <input type="text" id="admin_display_name" name="admin[display_name]" class="form-control" placeholder="Display name" value="<%= @admin.display_name %>">
      <!-- <small class="help-block">This is a help text</small> -->
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-3 control-label" for="admin_email">Email</label>
    <div class="col-md-9">
      <input type="text" id="admin_email" name="admin[email]" class="form-control" placeholder="Email" value="<%= @admin.email %>" <%= @admin.new_record? ? nil : "disabled" %>>
      <!-- <small class="help-block">This is a help text</small> -->
    </div>
  </div>

  <% if @admin.new_record? %>

    <div class="form-group">
      <label class="col-sm-3 control-label">Password</label>
      <div class="col-sm-6">
        <em>(8 characters minimum)</em>
        <br />
        <%= f.password_field :password, autocomplete: "off", :class=>"form-control", :placeholder => "Enter Password" %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label">Password Confirmation</label>
      <div class="col-sm-6">
        <%= f.password_field :password_confirmation, autocomplete: "off", :class=>"form-control", :placeholder => "Retype Password" %>
      </div>
    </div>

<% end %>


 <div class="panel-footer">
      <div class="row">
        <div class="col-sm-9 col-sm-offset-3">
          <button class="btn btn-info btn-labeled fa fa-user fa-lg" type="submit">Submit</button>
          <button class="btn btn-warning btn-labeled fa fa-repeat fa-lg" type="reset" id="back_btn">Back</button>
        </div>
      </div>
    </div>
<% end %>

<script type="text/javascript">
  
  $("#back_btn").click(function(e){
    e.preventDefault();
    <% if @admin.new_record? %>
      window.location.href='<%= super_admin_admins_path %>';
    <% else %>
      window.location.href='<%= super_admin_admin_path(@admin) %>';
    <% end %>
  });
</script>

app/views/super_admin/admins/edit.html.erb
<div class="row" id="content_div">
	<div class="col-lg-12">
		<div class="panel">
			<div class="panel-heading">
				<h3 class="panel-title">Editing Admin</h3>
			</div>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/super_admin/admins/index.html.erb
<div class="row" id="content_div">
  <div class="col-lg-12">

  <div class="panel">
      <div class="panel-heading">
        <div class="panel-control">
          <a class="fa fa-question-circle fa-lg fa-fw unselectable add-tooltip" href="#" data-original-title="<h4 class='text-thin'>Information</h4><p style='width:150px'>Click on the client name for more detail.</p>" data-html="true" title=""></a>
        </div>
        <h3 class="panel-title">Administrator</h3>
      </div>

      <div class="panel-body">
        <div class="pad-btm form-inline">
          <div class="row">
            <div class="col-sm-6 table-toolbar-left">
              <button id="add_client_btn" class="btn btn-purple btn-labeled fa fa-plus">
                New Admin
              </button>
              <!-- <div class="btn-group btn-group">
                <button class="btn btn-default"><i class="fa fa-exclamation-circle"></i></button>
                <button class="btn btn-default"><i class="fa fa-trash"></i></button>
              </div> -->
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Display Name</th>
                <th>Email</th>
                <th class="text-center">Action</th>
              </tr>
            </thead>

             <tbody>
              <% @admins.each do |admin| %>
                <tr>
                  <td><%= admin.display_name %></td>
                  <td><%= admin.email %></td>
                  <td class="text-center">
                    <%= link_to 'Show', super_admin_admin_path(admin), :class=>"btn btn-small btn-warning" %>
                    <%= link_to 'Destroy', super_admin_admin_path(admin), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-small btn-danger #{admin.id == current_admin.id ? 'disabled' : nil}" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
      </div>
    </div>

  </div>
</div>

<script type="text/javascript">
  
  $("#add_client_btn").click(function() {
    window.location.href='<%= new_super_admin_admin_path %>';
  });
</script>

app/views/super_admin/admins/new.html.erb
<div class="row" id="content_div">
	<div class="col-lg-12">
		<div class="panel">
			<div class="panel-heading">
				<h3 class="panel-title">New Admin</h3>
			</div>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/super_admin/admins/show.html.erb
<div class="row" id="content_div">
  <div class="col-lg-12">
    <div class="panel">
      <div class="panel-heading">
        <h3 class="panel-title">Admin detail</h3>
      </div>

      <div class="panel-body">
          <p>
            <strong>Full Name:</strong>
            <%= @admin.username %>
          </p>
          <p>
            <strong>Display Name:</strong>
            <%= @admin.display_name %>
          </p>

          <p>
            <strong>Email:</strong>
            <%= @admin.email %>
          </p>


          <%= link_to 'Edit', edit_super_admin_admin_path(@admin), :class=>"btn btn-small btn-info" %>
          <%= link_to 'Back', super_admin_admins_path, :class=>"btn btn-small btn-warning" %>
      </div>
    </div>