config/routes.rb
Rails.application.routes.draw do

  resources :blogs 
  resources :product_features do
    collection do 
      get "product_index"
    end
  end
  resources :product_photos
  resources :molpay_transaction_histories do
    collection do 
      post "molpay"
    end
  end

  resources :receipts
  
  resources :email_settings
  
  resources :regions
  
  resources :sources_types
  
  resources :product_settings
  
  resources :reservations do
    member do
      get "buyer"
    end
    collection do
      post "create_lot"
      get "confirm_reservation"
    end
  end

  resources :reports do
    member do
      get "menu"
      get "summary_report"
      get "analysis_age_report"
      get "analysis_unit_report"
      get "analysis_sources_type_report"
      get "analysis_region_report"
      get "analysis_race_report"
      get "sales"
      get "monthly_sales"
      get "agency_sales"
      get "cancellation"
      get "rejection"
      get "export_summary_report_excel"
      get "export_analysis_unit_excel"
      get "export_analysis_age_race_excel"
      get "export_sources_type_excel"
      get "export_regions_excel"
      get "sales_excel"
      get "monthly_excel"
    end
  end
  
  resources :buyers
  resources :company_settings 

  resources :sales do
    member do
      post "confirm"
      post "reject"
      post "cancel"
      get "new_payment"
      post "add_payment"
    end
    collection do
      get "export_purchaser_excel"
    end
  end

  devise_for :admins, :controllers => { :sessions => "super_admin/sessions", :registrations => "super_admin/registrations"  } # :skip => :registrations,
  devise_for :users, :controllers => { :registrations => :registrations, :sessions => :sessions, :passwords => :passwords  }

  resources :users do
    collection do
      post "create_member"
      post "create_user_access"
    end
    member do
      delete "remove_customize"
      patch  "update_member"
      delete "suspend"
      get    "activate"
    end
  end

  resources :lots do 
    member do
      post "bulk_update"
    end
  end

  resources :product_types do 
    member do 
      post "bulk_update"
    end
  end

  resources :products do 
    collection do
      post "create_lot"
      get "published"
    end
    member do
      post "update_email_setting"
      post "update_setting"
      post "update_region"
      post "update_sources_type"
      post "update_reservation_customization"
      get "site_plans"
      get "floor_plans"
    end
    resources :site_plans
    resources :floor_plans
    resources :enquiries, only: [:create, :index, :show]
  end

  resources :phases do 
    collection do 
      post "update_product"
    end
  end

  resources :projects do
    collection do
      post "update_project"
      post "update_phase"
    end
  end

  mount RailsEmailPreview::Engine, at: 'emails'

  resources :companies do
    member do
      post "update_setting"
      patch "update_profile"
    end
    collection do
      get "profile"
    end
  end

  namespace :super_admin do
    resources :admins
    resources :companies do
      member do
        post "update_setting"
      end
    end
  end

  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  match 'molpay/subscribe' => "molpay#subscribe", via: [:post, :get]
  match 'molpay/create_molpay_transaction' => "molpay#create_molpay_transaction", via: [:post, :get]
  match 'molpay/return_url' => "molpay#return_url", via: [:post, :get]
  match 'molpay/molpay' => "molpay#molpay", via: [:get, :post]
  
  get 'home' => "pages#home"
  get 'team' => "pages#team"
  get 'service' => "pages#service"
  get 'contact' => "pages#contact"
  get 'about_us' => "pages#about_us"
  get 'listings' => "pages#listings"
  get 'listing_details' => "pages#listing_details"
  get 'blog' => "pages#blog"
  get 'blog_details' => "pages#blog_details"
  match 'pages/sign_up_email' => "pages#sign_up_email", via: [:get, :post]
  match 'pages/personal_detail_email' => "pages#personal_detail_email", via: [:get, :post]

  get 'supermin_board' => 'super_admin/dashboard#index', as: :supermin_board
  
  root 'dashboard#index'
  

end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id                  :integer          not null, primary key
#  name                :string
#  registration_number :string(15)
#  address             :text
#  phone_number        :string(15)
#  fax_number          :string(15)
#  type_id             :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  logo_file_name      :string
#  logo_content_type   :string
#  logo_file_size      :integer
#  logo_updated_at     :datetime
#  slug                :string
#  parent_id           :integer
#  status_id           :integer          default(1)
#
# Indexes
#
#  index_companies_on_parent_id  (parent_id)
#  index_companies_on_slug       (slug) UNIQUE
#

class Company < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged

  validates :name, presence: true, uniqueness: { scope: :parent_id }

  has_many :users
  has_many :projects
  has_many :agencies, class_name: "Company", foreign_key: "parent_id"
  has_many :products

  has_attached_file :logo, 
          #:styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png",
          :default_url => ActionController::Base.helpers.asset_path('your-your_company_logo.jpg'),
          #:processors => [:thumbnail, :paperclip_optimizer],
          :path => "companies/:id/:filename"
  
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  DEVELOPER = 1
  AGENCY    = 2

  ACTIVE = 1
  SUSPENDED = 2

  TYPE_OPTIONS = [
    ["Developer", DEVELOPER],
    ["Agency", AGENCY]
  ].freeze

  def type
    case type_id
    when DEVELOPER
      "Developer"
    when AGENCY
      "Agency"
    end
  end

  def is_developer?
    type_id == DEVELOPER
  end

  def is_agency?
    type_id == AGENCY
  end

  def status
    case status_id
    when ACTIVE
      "Active"
    when SUSPENDED
      "Suspended"
    end
  end

  def is_active?
    status_id == ACTIVE
  end

  def is_suspended
    status_id == SUSPENDED
  end

  def should_generate_new_friendly_id?
    name_changed?
  end

  def members
    result = []
    result << users.to_a
    agencies.each do |agency|
      result << agency.users.to_a
    end
    result = result.flatten.uniq
    result.sort_by {|agent| agent.name }
  end

  def can_destroy?
    if products.any?
      return false, "The company cannot be delete if there is product running."
    else
      return true, "The company can be destroy."
    end
  end

  private

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  # before_action :authenticate_project_owner!

  before_action :set_company, only: [:show, :edit, :update, :destroy, :update_setting]

  # GET /companies
  # GET /companies.json
  def index
    @companies = current_user.company.agencies

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show

    # @setting = @company.company_setting
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  def profile
    if current_user
      @company = current_user.company
      # @setting = @company.company_setting
    end
  end

  # GET /companies/new
  def new
    @company = current_user.company.agencies.new
    @user = User.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    # render :text => params
    @company = current_user.company.agencies.new(company_params)
    @company.type_id = Company::AGENCY

    @user = User.new(username: params[:username], email: params[:company_email], password: params[:company_password], password_confirmation: params[:company_password_confirmation], display_name: "Admin")
    @user.type_id = User::ADMIN
      if @company.valid? && @user.valid?
        if @company.save
          @user.company_id = @company.id
          @user.save
          redirect_to @company, notice: 'Company was successfully created.'
        else
          flash.now[:alert] =  @company.errors.full_messages.join("<br>")
          render action: 'new'
        end
      else
        msg = ""
        msg << @company.errors.full_messages.join("<br>") if @company.errors.any?
        msg << @user.errors.full_messages.join("<br>") if @user.errors.any?
        flash.now[:alert] = msg
        render action: 'new'
      end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_profile
    @company = current_user.company
    respond_to do |format|
      if @company.update(company_params)
        format.html {  flash[:notice] = 'Company profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { flash[:alert] = @company.errors.full_messages.join("<br>") }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
    redirect_to action: :profile
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    can_destroy, message = @company.can_destroy?
    if can_destroy
      @company.destroy
      flash[:notice] = "The company has been destroyed successfully."
    else
      flash[:alert] = message
    end
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  def update_setting
    # render :text => params
    @setting = @company.company_setting
    flash[:notice] = "Setting was updated successfully."
    @setting.update(:allow_multiple_booking => setting_params[:allow_multiple_booking] )
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :registration_number, :address, :phone_number, :fax_number, :type_id, :parent_id,:slug)
    end

    def setting_params
      params.require(:company_setting).permit!
    end
end

app/controllers/super_admin/companies_controller.rb
class SuperAdmin::CompaniesController < ApplicationController
  before_action :authenticate_super_admin!
  before_action :set_company, only: [:show, :edit, :update, :destroy, :update_setting]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
    @user = User.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create

    @company = Company.new(company_params)
    @company.type_id = params[:company_type_id]

    @user = User.new(email: params[:company_email], password: params[:company_password], password_confirmation: params[:company_password_confirmation], display_name: "Admin", username: params[:company_username])
    @user.type_id = User::ADMIN
      if @company.valid? && @user.valid?
        if @company.save
          @user.company_id = @company.id
          @user.save!
          redirect_to super_admin_company_path(@company), notice: 'Company was successfully created.'
        else
          flash.now[:alert] =  @company.errors.full_messages.join("<br>")
          render action: 'new'
        end
      else
        msg = ""
        msg << @company.errors.full_messages.join("<br>") if @company.errors.any?
        msg << @user.errors.full_messages.join("<br>") if @user.errors.any?
        flash.now[:alert] = msg
        render action: 'new'
      end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @company.type_id = params[:company_type_id]
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to super_admin_company_path(@company), notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to super_admin_companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :registration_number, :address, :phone_number, :fax_number, :type_id, :parent_id,:slug, :username)
    end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company, html: {class: "panel-body form-horizontal form-padding"}) do |f| %>

  <div class="form-group">
    <label class="col-md-3 control-label" for="company_name">Name</label>
    <div class="col-md-9">
      <input type="text" id="company_name" name="company[name]" class="form-control" placeholder="Company name" value="<%= @company.name %>">
      <!-- <small class="help-block">This is a help text</small> -->
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-3 control-label" for="company_registration_number">Registration No</label>
    <div class="col-md-9">
      <input type="text" id="company_registration_number" name="company[registration_number]" class="form-control" placeholder="Company registration number" value="<%= @company.registration_number %>">
      <!-- <small class="help-block">This is a help text</small> -->
    </div>
  </div>

  <!--Textarea-->
  <div class="form-group">
    <label class="col-md-3 control-label" for="company_address">Address</label>
    <div class="col-md-9">
      <textarea id="company_address" name="company[address]" rows="9" class="form-control" placeholder=""><%= @company.address %></textarea>
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-3 control-label" for="company_phone_number">Phone Number</label>
    <div class="col-md-9">
      <input type="text" id="company_phone_number" name="company[phone_number]" class="form-control" placeholder="Company phone number" value="<%= @company.phone_number %>">
      <!-- <small class="help-block">This is a help text</small> -->
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-3 control-label" for="company_fax_number">Fax Number</label>
    <div class="col-md-9">
      <input type="text" id="company_fax_number" name="company[fax_number]" class="form-control" placeholder="Company fax number" value="<%= @company.fax_number %>">
      <!-- <small class="help-block">This is a help text</small> -->
    </div>
  </div>

    <% if @company.new_record? %>
      <div class="panel-heading">
        <h3 class="panel-title">Create administrator login</h3>
      </div>
      <div class="form-group">
        <label class="col-md-3 control-label" for="username">Full Name</label>
        <div class="col-md-9">
          <input type="text" id="username" name="username" class="form-control" placeholder="Full name" value="<%= @user.username %>">
          <!-- <small class="help-block">This is a help text</small> -->
        </div>
      </div>
      <div class="form-group">
        <label class="col-md-3 control-label" for="company_email">Email</label>
        <div class="col-md-9">
          <input type="email" id="company_email" name="company_email" class="form-control" placeholder="email" value="<%= @user.email%>">
          <!-- <small class="help-block">This is a help text</small> -->
        </div>
      </div>
      <div class="form-group">
        <label class="col-md-3 control-label" for="company_password">Password</label>
        <div class="col-md-9">
          <input type="password" id="company_password" name="company_password" class="form-control" placeholder="password" >
          <!-- <small class="help-block">This is a help text</small> -->
        </div>
      </div>
      <div class="form-group">
        <label class="col-md-3 control-label" for="company_password_confirmation">Password Confirmation</label>
        <div class="col-md-9">
          <input type="password" id="company_password_confirmation" name="company_password_confirmation" class="form-control" placeholder="password confirmation" >
          <!-- <small class="help-block">This is a help text</small> -->
        </div>
      </div>

    <% end %>

    <div class="panel-footer">
      <div class="row">
        <div class="col-sm-9 col-sm-offset-3">
          <button class="btn btn-info btn-labeled fa fa-user fa-lg" type="submit">Submit</button>
          <button class="btn btn-warning btn-labeled fa fa-repeat fa-lg" type="reset" id="back_btn">Back</button>
        </div>
      </div>
    </div>

<% end %>

<script type="text/javascript">
  
  $("#back_btn").click(function(e){
    e.preventDefault();
    <% if @company.new_record? %>
      window.location.href='<%= companies_path %>';
    <% else %>
      window.location.href='<%= company_path(@company) %>';
    <% end %>
  });
</script>


           
               

app/views/companies/edit.html.erb
<div class="row" id="content_div">
	<div class="col-lg-6">
		<div class="panel">
			<div class="panel-heading">
				<h3 class="panel-title">Editing Agency</h3>
			</div>

      <%= render 'form' %>

    </div>
  </div>
</div>

app/views/companies/index.html.erb
<div class="row" id="content_div">
  <div class="col-lg-12">

    <div class="panel">
      <div class="panel-heading">
        <div class="panel-control">
          <a class="fa fa-question-circle fa-lg fa-fw unselectable add-tooltip" href="#" data-original-title="<h4 class='text-thin'>Information</h4><p style='width:150px'>Click on the client name for more detail.</p>" data-html="true" title=""></a>
        </div>
        <h3 class="panel-title">Agency</h3>
      </div>

      <div class="panel-body">
        <div class="pad-btm form-inline">
          <div class="row">
            <div class="col-sm-6 table-toolbar-left">
              <button id="add_client_btn" class="btn btn-purple btn-labeled fa fa-plus">
                New Agency
              </button>
              <!-- <div class="btn-group btn-group">
                <button class="btn btn-default"><i class="fa fa-exclamation-circle"></i></button>
                <button class="btn btn-default"><i class="fa fa-trash"></i></button>
              </div> -->
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Registration No.</th>
                <th class="text-center">Action</th>
              </tr>
            </thead>

            <tbody>
              <% @companies.each do |company| %>
                <tr>
                  <td><%= company.name %></td>
                  <td><%= company.registration_number %></td>
                  <td class="text-center">
                    <%= link_to 'Show', company, :class=>"btn btn-small btn-warning" %>
                    <%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure you want to destroy the company? This action cannot be undo.' }, :class=>"btn btn-small btn-danger" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
      </div>
    </div>

  </div>
</div>

<script type="text/javascript">
  
  $("#add_client_btn").click(function() {
    window.location.href='<%= new_company_path %>';
  });
</script>

app/views/companies/new.html.erb
<div class="row" id="content_div">
	<div class="col-lg-6">
		<div class="panel">
			<div class="panel-heading">
				<h3 class="panel-title">New Agency</h3>
			</div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/companies/profile.html.erb
<div class="row" id="content_div">
	  <!--company profile-->
		<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
		<div class="col-lg-12">
		<div class="panel">
			<div class="panel-heading">
				<h3 class="panel-title">Company profile</h3>
			</div>

      <%= form_for(@company, url: update_profile_company_path(@company), html: {class: "panel-body form-horizontal form-padding"}) do |f| %>

		  <div class="form-group">
		    <label class="col-md-3 control-label" for="company_name">Name</label>
		    <div class="col-md-9">
		      <input type="text" id="company_name" name="company[name]" class="form-control" placeholder="Company name" value="<%= @company.name %>" <%= current_user_can_edit? ? nil : 'disabled' %> >
		      <!-- <small class="help-block">This is a help text</small> -->
		    </div>
		  </div>

		  <div class="form-group">
		    <label class="col-md-3 control-label" for="company_registration_number">Registration No</label>
		    <div class="col-md-9">
		      <input type="text" id="company_registration_number" name="company[registration_number]" class="form-control" placeholder="Company registration number" value="<%= @company.registration_number %>" <%= current_user_can_edit? ? nil : 'disabled' %> >
		      <!-- <small class="help-block">This is a help text</small> -->
		    </div>
		  </div>

		  <!--Textarea-->
		  <div class="form-group">
		    <label class="col-md-3 control-label" for="company_address">Address</label>
		    <div class="col-md-9">
		      <textarea id="company_address" name="company[address]" rows="9" class="form-control" <%= current_user_can_edit? ? nil : 'disabled' %> ><%= @company.address %></textarea>
		    </div>
		  </div>

		  <div class="form-group">
		    <label class="col-md-3 control-label" for="company_phone_number">Phone Number</label>
		    <div class="col-md-9">
		      <input type="text" id="company_phone_number" name="company[phone_number]" class="form-control" placeholder="Company phone number" value="<%= @company.phone_number %>" <%= current_user_can_edit? ? nil : 'disabled' %> >
		      <!-- <small class="help-block">This is a help text</small> -->
		    </div>
		  </div>

		  <div class="form-group">
		    <label class="col-md-3 control-label" for="company_fax_number">Fax Number</label>
		    <div class="col-md-9">
		      <input type="text" id="company_fax_number" name="company[fax_number]" class="form-control" placeholder="Company fax number" value="<%= @company.fax_number %>" <%= current_user_can_edit? ? nil : 'disabled' %> >
		      <!-- <small class="help-block">This is a help text</small> -->
		    </div>
		  </div>

		    <div class="form-group pad-ver">
		      <label class="col-md-3 control-label">Type</label>
		      <div class="col-md-9"><p class="form-control-static"><%= @company.type  %></p></div>
		    </div>

		    <div class="panel-footer">
		      <div class="row">
		        <div class="col-sm-9 col-sm-offset-3">
		          <% if current_user_can_edit? %>
		            <button class="btn btn-info btn-labeled fa fa-user fa-lg" type="submit">Update</button>
		          <% end %>
		        </div>
		      </div>
		    </div>

		<% end %>
          
    </div>
  </div>
</div>

app/views/companies/show.html.erb
<div class="row" id="content_div">
  <div class="col-lg-6">
    <div class="panel">
      <div class="panel-heading">
        <h3 class="panel-title">Agency detail</h3>
      </div>

      <div class="panel-body">
          <p>
            <strong>Name:</strong>
            <%= @company.name %>
          </p>

          <p>
            <strong>Registration number:</strong>
            <%= @company.registration_number %>
          </p>

          <p>
            <strong>Address:</strong>
            <%= @company.address %>
          </p>

          <p>
            <strong>Phone number:</strong>
            <%= @company.phone_number %>
          </p>

          <p>
            <strong>Fax number:</strong>
            <%= @company.fax_number %>
          </p>
          <p>
            <strong>Type:</strong>
            <%= @company.type %>
          </p>

          <%= link_to 'Edit', edit_company_path(@company), :class=>"btn btn-small btn-info" %>
          <%= link_to 'Back', companies_path, :class=>"btn btn-small btn-warning" %>
      </div>
    </div>

      <div class="panel">
        <div class="panel-heading">
          <h3 class="panel-title">User</h3>
        </div>
       
        <div class="panel-body">
            <div class="form-group">
              <div class="col-md-12">
                <div class="table-responsive">
                <table class="table table-striped table-hover">
                  <thead>
                    <tr>
                      <th>Display Name</th>
                      <th>Email</th>
                      <th class="text-center">Type</th>
                      <!-- <th class="text-center">Action</th> -->
                    </tr>
                  </thead>

                  <tbody>
                    <% @company.users.each do |user| %>
                      <tr>
                        <td><%= user.display_name %></td>
                        <td><%= user.email %></td>
                        <td class="text-center"><%= user.type %></td>
                       <!--  <td class="text-center">
                          <%#= link_to 'Show', user, :class=>"btn btn-small btn-warning" %>
                          <%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-small btn-danger" %></td> -->
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                </div>
            </div>
          </div>
        </div>
    </div>

    </div>
  </div>
</div>