config/routes.rb
Rails.application.routes.draw do

  resources :blogs 
  resources :product_features do
    collection do 
      get "product_index"
    end
  end
  resources :product_photos
  resources :molpay_transaction_histories do
    collection do 
      post "molpay"
    end
  end

  resources :receipts
  
  resources :email_settings
  
  resources :regions
  
  resources :sources_types
  
  resources :product_settings
  
  resources :reservations do
    member do
      get "buyer"
    end
    collection do
      post "create_lot"
      get "confirm_reservation"
    end
  end

  resources :reports do
    member do
      get "menu"
      get "summary_report"
      get "analysis_age_report"
      get "analysis_unit_report"
      get "analysis_sources_type_report"
      get "analysis_region_report"
      get "analysis_race_report"
      get "sales"
      get "monthly_sales"
      get "agency_sales"
      get "cancellation"
      get "rejection"
      get "export_summary_report_excel"
      get "export_analysis_unit_excel"
      get "export_analysis_age_race_excel"
      get "export_sources_type_excel"
      get "export_regions_excel"
      get "sales_excel"
      get "monthly_excel"
    end
  end
  
  resources :buyers
  resources :company_settings 

  resources :sales do
    member do
      post "confirm"
      post "reject"
      post "cancel"
      get "new_payment"
      post "add_payment"
    end
    collection do
      get "export_purchaser_excel"
    end
  end

  devise_for :admins, :controllers => { :sessions => "super_admin/sessions", :registrations => "super_admin/registrations"  } # :skip => :registrations,
  devise_for :users, :controllers => { :registrations => :registrations, :sessions => :sessions, :passwords => :passwords  }

  resources :users do
    collection do
      post "create_member"
      post "create_user_access"
    end
    member do
      delete "remove_customize"
      patch  "update_member"
      delete "suspend"
      get    "activate"
    end
  end

  resources :lots do 
    member do
      post "bulk_update"
    end
  end

  resources :product_types do 
    member do 
      post "bulk_update"
    end
  end

  resources :products do 
    collection do
      post "create_lot"
      get "published"
    end
    member do
      post "update_email_setting"
      post "update_setting"
      post "update_region"
      post "update_sources_type"
      post "update_reservation_customization"
      get "site_plans"
      get "floor_plans"
    end
    resources :site_plans
    resources :floor_plans
    resources :enquiries, only: [:create, :index, :show]
  end

  resources :phases do 
    collection do 
      post "update_product"
    end
  end

  resources :projects do
    collection do
      post "update_project"
      post "update_phase"
    end
  end

  mount RailsEmailPreview::Engine, at: 'emails'

  resources :companies do
    member do
      post "update_setting"
      patch "update_profile"
    end
    collection do
      get "profile"
    end
  end

  namespace :super_admin do
    resources :admins
    resources :companies do
      member do
        post "update_setting"
      end
    end
  end

  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  match 'molpay/subscribe' => "molpay#subscribe", via: [:post, :get]
  match 'molpay/create_molpay_transaction' => "molpay#create_molpay_transaction", via: [:post, :get]
  match 'molpay/return_url' => "molpay#return_url", via: [:post, :get]
  match 'molpay/molpay' => "molpay#molpay", via: [:get, :post]
  
  get 'home' => "pages#home"
  get 'team' => "pages#team"
  get 'service' => "pages#service"
  get 'contact' => "pages#contact"
  get 'about_us' => "pages#about_us"
  get 'listings' => "pages#listings"
  get 'listing_details' => "pages#listing_details"
  get 'blog' => "pages#blog"
  get 'blog_details' => "pages#blog_details"
  match 'pages/sign_up_email' => "pages#sign_up_email", via: [:get, :post]
  match 'pages/personal_detail_email' => "pages#personal_detail_email", via: [:get, :post]

  get 'supermin_board' => 'super_admin/dashboard#index', as: :supermin_board
  
  root 'dashboard#index'
  

end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id                     :integer          not null, primary key
#  project_id             :integer
#  product_id             :integer
#  lot_unit_id            :integer
#  phase_id               :integer
#  user_id                :integer
#  status_id              :integer          default(1)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  buyer_id               :integer
#  downpayment            :integer
#  downpayment_percentage :integer
#  spa                    :string
#  booking_fee            :integer
#  reject_reason          :string
#  confirm_date           :datetime
#  admin_confirm_user_id  :integer
#  payment_type_id        :integer
#  cancel_date            :datetime
#  cheque_number          :string
#  transaction_number     :string
#
# Indexes
#
#  index_sales_on_buyer_id     (buyer_id)
#  index_sales_on_lot_unit_id  (lot_unit_id)
#  index_sales_on_phase_id     (phase_id)
#  index_sales_on_product_id   (product_id)
#  index_sales_on_project_id   (project_id)
#  index_sales_on_status_id    (status_id)
#  index_sales_on_user_id      (user_id)
#

class Sale < ActiveRecord::Base
  belongs_to :buyer
  belongs_to :user
  belongs_to :product
  belongs_to :project
  belongs_to :phase
  belongs_to :lot_unit, :class_name => "Lot"
  has_many :payments
  has_one :molpay_transaction_history

  scope :confirmed, -> { where status_id: COMPLETED }

  # status
  PENDING = 1
  COMPLETED = 2
  REJECTED = 3
  CANCELLED = 4
  PENDING_RESERVATION = 5
  CONFIRM_RESERVATION = 6

  CASH = 1
  BANK_LOAN = 2
  GOVERNMENT_LOAN = 3
  STAFF_LOAN = 4

  def payment_type
    case payment_type_id
    when CASH
      "Cash"
    when BANK_LOAN
      "Bank Loan"
    when GOVERNMENT_LOAN
      "Government Loan"
    when STAFF_LOAN
      "Staff Loan"
    end
  end

  def status
  	case status_id
    when PENDING
      "Pending"
    when COMPLETED
      "completed"
    when REJECTED
      "Rejected"
    when CANCELLED
      "Cancelled"
    when PENDING_RESERVATION
      "Pending Reservation"
    when CONFIRM_RESERVATION
      "Confirm Reservation"
    end
  end

  def confirm_date_short_format
    confirm_date.strftime("%d/%m/%Y") rescue ""
  end

  def lot
    Lot.find_by(id: lot_unit_id)
  end

  def actual_price
    original_price = lot.selling_price
    # if buyer.is_bumiputera? && lot.is_special_unit == false
    if buyer.is_bumiputera?
      rate_total = original_price * bumiputera_discount / 100
      original_price -= rate_total
    else
      original_price
    end
  end

  def product_setting
    @setting ||= product.product_setting
  end

  def bumiputera_discount
    product_setting.bumiputera_discount || 7
  end


end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :authenticate_project_owner!, except: [:index, :edit, :confirm_sales, :reject_sales, :new_payment, :add_payment]
  before_action :set_sale, only: [:show, :edit, :update, :destroy, :new_payment, :add_payment]

  # GET /sales
  # GET /sales.json
  def index
    return redirect_to root_path, alert: "Sorry, you don't have the access right." if is_low_level_staff?
    if is_middle_level_management?
      @agencies = []
      @agencies << current_user.company.agencies
      @agencies << current_user.company
      @agencies.flatten!
      @q = Sale.where("sales.product_id IN(?)", current_user.company.product_ids).order("created_at DESC").ransack(params[:q])
    else
      @q = current_user.sales.ransack(params[:q])
    end
    @sales = @q.result(distinct: true).order("id ASC").page(params[:page]).per(10)
    # render :text => @sales.to_json
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sales }
    end
  end

  def export_purchaser_excel
    @sales = Sale.where("product_id IN(?)", current_user.company.product_ids).order("created_at DESC")
    # @ideal_export_excel = DeveloperCustomer.where("remark = 'ideal'")
    respond_to do |format|
      format.csv { render text: @sales.to_csv }
      format.xls
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @payments =  @sale.payments
    render action: 'show', layout: false
  end

  # GET /sales/new
  def new
    # @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
    
    unless is_top_level_management?
      flash[:alert] = "Sorry, you don't have the access right."
      redirect_to sales_path
    end
  end

  # POST /sales
  # POST /sales.json
  def create
    # @sale = Sale.new(sale_params)

    # respond_to do |format|
    #   if @sale.save
    #     format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
    #     format.json { render json: @sale, status: :created }
    #   else
    #     format.html { render action: 'new' }
    #     format.json { render json: @sale.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sales_path, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    # @sale.destroy
    # respond_to do |format|
    #   format.html { redirect_to sales_url }
    #   format.json { head :no_content }
    # end
  end

  def new_payment
    @molpay_transaction = MolpayTransactionHistory.find_by(sale_id: @sale.id)
    # render :text => @sale.id.to_json
    unless @sale.user_id == current_user.id
      flash[:alert] = "Only the agent of the sale can edit."
      redirect_to sales_path
    end
  end

  def add_payment
    # render :text => params[:payment_image]
    setting = @sale.product.product_setting
    if @sale.user_id == current_user.id
      if params[:payment_image]
        params[:payment_image].each do |file|
          if !file.nil?
            payment = @sale.payments.new
            payment.image = file
            payment.save
          end
        end
      end
      @sale.cheque_number = params[:payment][:cheque_number] if params[:payment][:cheque_number]
      @sale.transaction_number = params[:payment][:transaction_number] if params[:payment][:transaction_number]
      if @sale.save
        SalesNotifier.inform_admins_payment(@sale.id).deliver_now if setting.notify_admin_on_payment_upload?
      end
    else
      flash[:alert] = "Only the agent of the sale can edit."
    end
    redirect_to sales_path
  end

  def confirm
    if is_top_level_management?
      @sale = Sale.find params[:id]
      SaleEngine.new(@sale, sale_params).confirm
      #@sale.confirm_sale(confirm_sale_params)
      redirect_to sales_path, notice: "Sale has been confirmed."
    else
      flash[:alert] = "Sorry, you don't have the access right."
      redirect_to sales_path
    end
  end


  def reject
    sale = Sale.find(params[:id])
    if is_top_level_management? || sale.user_id == current_user.id
      SaleEngine.new(sale, reject_reason_params).reject
      redirect_to sales_path, notice: "Sale has been rejected successfully."
    else
      flash[:alert] = "Sorry, you don't have the access right."
      redirect_to sales_path
    end
  end

  def cancel
    sale = Sale.find(params[:id])
    if is_top_level_management? || sale.user_id == current_user.id
      if sale.status_id == Sale::COMPLETED
        SaleEngine.new(sale, cancel_reason_params).cancel
        flash[:notice] = "Sale has been cancelled successfully."
      else
        flash[:alert] = "The sale cannot be cancel due to invalid status."
      end
      redirect_to sales_path
    else
      flash[:alert] = "Sorry, you don't have the access right."
      redirect_to sales_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:admin_confirm_user_id ,:user_id, :downpayment, :downpayment_percentage, :payment_type_id, :cash, :bank_loan, :government_loan, :staff_loan , :spa, :confirm_date, :purchaser_name, :purchaser_address, :purchaser_ic_number, :purchaser_contact_number, :cancel_date, :cheque_number, :transaction_number)
    end

    def reject_reason_params
      params.require(:sale).permit(:reject_reason)
    end

    def cancel_reason_params
      params.require(:sale).permit(:cancel_reason)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_cancel_sale_form.html.erb
<%= form_tag cancel_sale_path(sale), {:class => 'panel-body form-horizontal form-padding'}  do %>

  <% product = Product.find(sale.product_id) %>
  <% @customization = product.reservation_customization %>

  <%# if @customization.reject_reason? %>
    <div class="form-group">
      <label class="col-md-3 control-label" for="sale_cancel_reason">Cancel Reason:</label>
      <div class="col-md-9">
        <input type="text" id="sale_cancel_reason" name="sale[cancel_reason]" class="form-control" placeholder="Cancel Reason" <%#= @customization.reject_reason_required? ? 'required' : nil %> >
          <%# if @customization.reject_reason_required? %>
            <!-- <small class="help-block">Required field</small> -->
          <%# end %>
      </div>
    </div>

  <% if @customization.cancel_date? %>
    <div class="form-group">
      <label class="col-md-3 control-label" for="sale_cancel_date">Cancel Date: </label>
      <div class="col-md-9">
        <div class="input-group date">
          <input type="text" class="form-control" name="sale[cancel_date]" id="sale_cancel_date" value="" <%= @customization.cancel_date_required? ? 'required' : nil %> >
          <span class="input-group-addon"><i class="fa fa-calendar fa-lg"></i></span>
        </div>
        
        <small class="text-muted">Click to select the Cancel date.</small>
        <% if @customization.cancel_date_required?  %>
          <small class="help-block">Required field</small>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="row">
      <div class="col-sm-9 col-sm-offset-3">
        <br>
        <button class="btn btn-info btn-labeled fa fa-user fa-lg" type="submit">Submit</button>
        <!-- <button class="btn btn-warning btn-labeled fa fa-repeat fa-lg" type="reset" id="back_btn">Back</button> -->
      </div>
    </div>
  </div>

<% end %>

app/views/sales/_reject_sale_form.html.erb
<%= form_tag reject_sale_path(sale), {:class => 'panel-body form-horizontal form-padding'}  do %>
  
  <% @product = Product.friendly.find(sale.product_id) %>
  <% @customization = @product.reservation_customization %>

  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_reject_reason">Reject Reason:</label>
    <div class="col-md-9">
      <input type="text" id="sale_reject_reason" name="sale[reject_reason]" class="form-control" placeholder="Reject Reason" <%= @customization.reject_reason_required? ? 'required' : nil %>>
    <% if @customization.reject_reason_required?  %>
      <small class="help-block">Required field</small>
    <% end %>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-sm-9 col-sm-offset-3">
        <br>
        <button class="btn btn-info btn-labeled fa fa-user fa-lg" type="submit">Submit</button>
        <!-- <button class="btn btn-warning btn-labeled fa fa-repeat fa-lg" type="reset" id="back_btn">Back</button> -->
      </div>
    </div>
  </div>

<% end %>

app/views/sales/_sale_index_action.html.erb
<% if sale.status_id == Sale::PENDING %>
  <% if is_top_level_management? %>
    
    <%= link_to "Confirm Prebook", confirm_reservation_reservations_path(:sale_id => sale.id), :class=>"btn btn-info btn-sm",data: { confirm: "Confirm Booking Fee RM#{sale.booking_fee} ?"  } %>

    <button data-target="#confirm_sale<%= sale.id %>" data-toggle="modal" class="btn btn-success btn-sm">Confirm Sale</button>
  
    <button data-target="#reject_sale<%= sale.id %>" data-toggle="modal" class="btn btn-danger btn-sm">Reject Sale</button>

<% elsif sale.user_id == current_user.id %>
    <button data-target="#reject_sale<%= sale.id %>" data-toggle="modal" class="btn btn-danger btn-sm">Reject Sale</button>
  <% end %>
<% elsif sale.status_id == Sale::REJECTED || sale.status_id == Sale::CANCELLED %>
  <!-- <button class="btn btn-default btn-hover-info add-tooltip" data-placement="top" data-toggle="tooltip" data-original-title="">Show reason</button> -->

<button class="btn btn-default btn-active-success add-popover" data-toggle="popover" data-placement="top" data-original-title="Rejected/Cancelled Reason" data-content="<%= sale.reject_reason %>">Show reason</button>

<!-- after confirm reservation  -->
<% elsif sale.status_id == Sale::CONFIRM_RESERVATION %>
  <% if is_top_level_management? %>
    <button data-target="#confirm_sale<%= sale.id %>" data-toggle="modal" class="btn btn-success btn-sm">Confirm Sale</button>
  <% end %>
  <button data-target="#reject_sale<%= sale.id %>" data-toggle="modal" class="btn btn-danger btn-sm">Reject Sale</button>
<% elsif sale.status_id == Sale::PENDING_RESERVATION %>
  <button data-target="#reject_sale<%= sale.id %>" data-toggle="modal" class="btn btn-danger btn-sm">Reject Sale</button>
<% elsif sale.status_id == Sale::COMPLETED %>
  <% if is_top_level_management? %>
    <a href="<%= edit_sale_path(sale) %>">
      <button class="btn btn-primary btn-sm">
      Edit
      </button>
    </a>
    <button data-target="#cancel_sale<%= sale.id %>" data-toggle="modal" class="btn btn-danger btn-sm">Cancel</button>
  <% end %>
<% end %>

app/views/sales/_sale_index_modal.html.erb
<div class="modal fade" id="confirm_sale<%= sale.id %>" role="dialog" tabindex="-1" aria-labelledby="confirm_sale" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <!--Modal header-->
      <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button">
        <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Confirm Sale</h4>
      </div>

      <!--Modal body-->
      <div class="modal-body">
        <%= render partial: "confirm_sale_form",  :locals => { :sale => sale } %>
        <%#= render :text => params %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="reject_sale<%= sale.id %>" role="dialog" tabindex="-1" aria-labelledby="reject_sale" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <!--Modal header-->
      <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button">
        <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Reject Sale</h4>
      </div>

      <!--Modal body-->
      <div class="modal-body">
        <%= render partial: "reject_sale_form",  :locals => { :sale => sale } %>
        <%#= render :text => params %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="cancel_sale<%= sale.id %>" role="dialog" tabindex="-1" aria-labelledby="cancel_sale" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <!--Modal header-->
      <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button">
        <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Cancel Sale</h4>
      </div>

      <!--Modal body-->
      <div class="modal-body">
        <%= render partial: "cancel_sale_form",  :locals => { :sale => sale } %>
      </div>
    </div>
  </div>
</div>

app/views/sales/index.html.erb
<% content_for :stylesheets do %>
  <link href="/plugins/bootstrap-datepicker/bootstrap-datepicker.css" rel="stylesheet">
<% end %>
<%#= current_user.company.users.map {|user| user.email if (user.status_id == 1)}.join(", ") %>
<div class="row" id="content_div">
  <div class="col-lg-12">

  <div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">Sales History</h3>
    </div> 
    <!-- index search function here -->
    <%= render "sale_index_search" %>

    <div class="panel-body">
      <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Booking Date</th>
            <th class="text-center">Agent</th>
            <th class="text-left">Purchaser</th>
            <th class="text-center">Product</th>
            <th class="text-center">Unit</th>
            <th class="text-center">Price</th>
            <!-- <th class="text-center">Payment</th> -->
            <th class="text-center">Status</th>
            <th class="text-center">Action<th>
          </tr>
        </thead>

        <tbody>
          <% @sales.each do |sale| %>
          <tr>
            <td><%= sale.created_at.strftime("%d-%m-%Y")  %></td>
            <!-- <td><%#= sale.confirm_date.strftime("%d-%m-%Y") rescue ""  %></td> -->
            <!-- <td><%#= sale.user.company.name rescue "Company not found" %></td> -->
            <td class="text-center">
              <%#= sale.id %>
              <%= sale.user.name rescue "User not found" %></td>
            <td class="text-left">
              <% if is_top_level_management? || (sale.user_id == current_user.id) %>
                <a href="<%= edit_buyer_path(sale.buyer, sale_id: sale.id) rescue '#' %>"><button class="btn btn-primary btn-sm"><%= (sale.buyer.try(:full_name) || "Unknown").truncate(30, omission: '...') %></button>
                </a>
              <% else %>
                <span class="label label-primary"><%= sale.buyer.try(:full_name) %></span>
              <% end %>

              <!-- Sources : <%#= sale.buyer.try(:sources_type_id) %>
              Region : <%#= sale.buyer.try(:region_id) %> -->
            </td>
            <% lot = sale.lot %>
            <td class="text-center">
              <%= lot.product.name rescue "Lot not found" %></td>
            <td class="text-center">
              <%= lot.name rescue "Lot not found" %>
            </td>
            <%# binding.pry %>
            <td class="text-center">
              <%= number_with_precision(sale.actual_price, precision: 0, separator: ".", delimiter: ",") rescue "Lot not found" %>
            </td>
            <!-- <td class="text-center">
              <%# unless sale.status_id == Sale::REJECTED || sale.status_id == Sale::CANCELLED %>
              #<%# if sale.payments.any? %>
                <button id="payment-<%#= sale.id %>" class="btn btn-sm btn-purple payment">Show</button>
              #<%# end %>
                <a href="<%#= new_payment_sale_path(sale) %>"><button class="btn btn-primary btn-sm">Add Payment</button>
              <%# end %>
              </a>
            </td> -->
            <td class="text-center">
              <% if sale.status_id == Sale::PENDING %>
                <span class="label label-warning">Prebook</span>
              <% elsif sale.status_id == Sale::REJECTED %>
                <span class="label label-danger">Rejected</span>
              <% elsif sale.status_id == Sale::CANCELLED %>
                <span class="label label-danger">Cancelled</span>
              <% elsif sale.status_id == Sale::COMPLETED %>
                <span class="label label-success">Sold</span>
              <% elsif sale.status_id == Sale::PENDING_RESERVATION %>
                <span class="label label-danger">Pending</span>
              <% elsif sale.status_id == Sale::CONFIRM_RESERVATION %>
                <span class="label label-info">Booked</span>
              <% end %>
            </td>

            <td class="text-center">
              <!-- button action here -->
            <%= render partial: "sale_index_action", locals: {sale: sale} %>
            </td>
          </tr>
          <!-- modal here -->
          <%= render partial: "sale_index_modal", locals: {sale: sale} %>
          <% end %>
        </tbody>
      </table>

          <%= paginate @sales, :theme => 'twitter-bootstrap-3'  %>
          <div class="panel-footer text-right">
            <% if is_top_level_management? %>  
              <%= link_to "Export Excel", export_purchaser_excel_sales_path(format: "xls"), :class=>"btn btn-warning " %>
            <% end %>
          </div>
        </div> <!-- table responsive-->
      </div>
    </div>

  </div>
</div>

<% content_for :javascripts do %>
  <script src="/plugins/bootstrap-datepicker/bootstrap-datepicker.js"></script>
  <script src="/js/demo/form-component.js"></script>
  <script type="text/javascript">
    $('#sale_confirm_date').datepicker({
      format: 'dd/mm/yyyy',
      autoclose: true
    });

    $('#sale_cancel_date').datepicker({
      format: 'dd/mm/yyyy',
      autoclose: true
    });

    // $(document).ready(function() {
      $('button.payment').on('click', function(){
        var sale_name = $(this).attr("id");
        var sale_id = sale_name.split("-")[1];
        var payment_url;
        // alert(sale_id);
        $.get("/sales/"+sale_id, function(data){
          
          bootbox.dialog({
           size: "large",
           title: "Payment",
           message: data,
           buttons: {
             confirm: {
               label: "Close"
             }
           }
         });
        });
        
      });

    // });
  </script>
<% end %>

app/views/sales/new_payment.html.erb
<% content_for :javascripts do %>
  <script type="text/javascript">
    $("#back_btn").click(function(e){
      e.preventDefault();
      window.location.href='<%= sales_path %>';
    });

  </script>
<% end %>
<div class="row" id="content_div">
  <div class="col-lg-12">
    <div class="panel">
      <div class="panel-heading">
        <h3 class="panel-title">Payment</h3>
      </div>
      <%= form_tag add_payment_sale_path(@sale), :class => 'panel-body form-horizontal form-padding', :multipart => true do  %>
       

        <% if @sale.user_id == current_user.id %>
            <br>
            <div class="form-group">
              <label class="col-md-3 control-label" for="payment_image">Cheque/Transaction Slip: </label>
              <div class="col-md-9 upload_payments_wrapper">
                <div class="upload_fields">
                  <input type="file" id="payment_image" name="payment_image[]" class="form-control">
                  <% 4.times do %>
                    <input type="file" id="payment_image" name="payment_image[]" class="form-control" >
                  <% end %>
                </div>
                <!-- <button class="add_more_photo_button btn btn-info">Add more photo</button> -->
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Cheque Number: 
              </label>
              <div class="col-md-9">
                <input type="text" class="form-control" name="payment[cheque_number]" id="cheque_number" >
              </div> 
            </div>

            <div class="form-group">
              <label class="col-md-3 control-label">Transaction Number: 
              </label>
              <div class="col-md-9">
                <input type="text" class="form-control" name="payment[transaction_number]" id="transaction_number" >
              </div> 
            </div>

            <!-- <div class="form-group">
              <label class="col-md-6 control-label">
                <h4>Or</h4>
              </label>
            </div>
            <hr>

            <div class="form-group">
              <label class="col-md-3 control-label">
                With Credit Card / Online Banking:
              </label>
              <div class="col-md-5">
                <%# if @molpay_transaction && @molpay_transaction.status == MolpayTransactionHistory::SUCCESS %>
                  <%#= link_to "View Molpay Transaction", molpay_transaction_history_path(@sale.id) %>
                <%# else %>
                  <%#= link_to "Pay Now", molpay_subscribe_path(:id => @sale.id), :class=>"btn btn-warning" %>
                <%# end %>
              </div>
              <div class="col-md-4">
                <img class="img-responsive" src="/img/slack-imgs.com.jpeg" alt="Image">
              </div>
            </div> -->
        <% end %>

        <br>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-9 col-sm-offset-3">
                <br>
              <button class="btn btn-info btn-labeled fa fa-user fa-lg" type="submit">Submit</button>
              <button class="btn btn-warning btn-labeled fa fa-repeat fa-lg" type="reset" id="back_btn">Back</button>
            </div>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>