config/routes.rb
Rails.application.routes.draw do

  resources :blogs 
  resources :product_features do
    collection do 
      get "product_index"
    end
  end
  resources :product_photos
  resources :molpay_transaction_histories do
    collection do 
      post "molpay"
    end
  end

  resources :receipts
  
  resources :email_settings
  
  resources :regions
  
  resources :sources_types
  
  resources :product_settings
  
  resources :reservations do
    member do
      get "buyer"
    end
    collection do
      post "create_lot"
      get "confirm_reservation"
    end
  end

  resources :reports do
    member do
      get "menu"
      get "summary_report"
      get "analysis_age_report"
      get "analysis_unit_report"
      get "analysis_sources_type_report"
      get "analysis_region_report"
      get "analysis_race_report"
      get "sales"
      get "monthly_sales"
      get "agency_sales"
      get "cancellation"
      get "rejection"
      get "export_summary_report_excel"
      get "export_analysis_unit_excel"
      get "export_analysis_age_race_excel"
      get "export_sources_type_excel"
      get "export_regions_excel"
      get "sales_excel"
      get "monthly_excel"
    end
  end
  
  resources :buyers
  resources :company_settings 

  resources :sales do
    member do
      post "confirm"
      post "reject"
      post "cancel"
      get "new_payment"
      post "add_payment"
    end
    collection do
      get "export_purchaser_excel"
    end
  end

  devise_for :admins, :controllers => { :sessions => "super_admin/sessions", :registrations => "super_admin/registrations"  } # :skip => :registrations,
  devise_for :users, :controllers => { :registrations => :registrations, :sessions => :sessions, :passwords => :passwords  }

  resources :users do
    collection do
      post "create_member"
      post "create_user_access"
    end
    member do
      delete "remove_customize"
      patch  "update_member"
      delete "suspend"
      get    "activate"
    end
  end

  resources :lots do 
    member do
      post "bulk_update"
    end
  end

  resources :product_types do 
    member do 
      post "bulk_update"
    end
  end

  resources :products do 
    collection do
      post "create_lot"
      get "published"
    end
    member do
      post "update_email_setting"
      post "update_setting"
      post "update_region"
      post "update_sources_type"
      post "update_reservation_customization"
      get "site_plans"
      get "floor_plans"
    end
    resources :site_plans
    resources :floor_plans
    resources :enquiries, only: [:create, :index, :show]
  end

  resources :phases do 
    collection do 
      post "update_product"
    end
  end

  resources :projects do
    collection do
      post "update_project"
      post "update_phase"
    end
  end

  mount RailsEmailPreview::Engine, at: 'emails'

  resources :companies do
    member do
      post "update_setting"
      patch "update_profile"
    end
    collection do
      get "profile"
    end
  end

  namespace :super_admin do
    resources :admins
    resources :companies do
      member do
        post "update_setting"
      end
    end
  end

  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  match 'molpay/subscribe' => "molpay#subscribe", via: [:post, :get]
  match 'molpay/create_molpay_transaction' => "molpay#create_molpay_transaction", via: [:post, :get]
  match 'molpay/return_url' => "molpay#return_url", via: [:post, :get]
  match 'molpay/molpay' => "molpay#molpay", via: [:get, :post]
  
  get 'home' => "pages#home"
  get 'team' => "pages#team"
  get 'service' => "pages#service"
  get 'contact' => "pages#contact"
  get 'about_us' => "pages#about_us"
  get 'listings' => "pages#listings"
  get 'listing_details' => "pages#listing_details"
  get 'blog' => "pages#blog"
  get 'blog_details' => "pages#blog_details"
  match 'pages/sign_up_email' => "pages#sign_up_email", via: [:get, :post]
  match 'pages/personal_detail_email' => "pages#personal_detail_email", via: [:get, :post]

  get 'supermin_board' => 'super_admin/dashboard#index', as: :supermin_board
  
  root 'dashboard#index'
  

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :authenticate_user!
  before_action :authenticate_project_owner!
  before_action :find_product, except: [:index, :menu]
  layout :false, except: [:index]

  def index
    @products = current_user.company.products.published
  end

  def menu
    @product = Product.find params[:id]
  end

	def summary_report
    @sales = @product.sales
	end

	def analysis_unit_report
		@lots = @product.lots
		@sales = @product.sales
	end

	def analysis_age_report
    @sales = @product.sales
    @buyers = []
    @sales.each do |sale|
      @buyers << sale.buyer
    end
	end

  def analysis_race_report
    @sales = @product.sales
    @buyers = []
    @sales.each do |sale|
      @buyers << sale.buyer
    end
  end

  def cancellation
    # @sales = @product.sales.where({status_id: [Sale::REJECTED, Sale::CANCELLED] }).order(:status_id)
    @sales = @product.sales.where(status_id: Sale::CANCELLED).order(:status_id)
  end

  def rejection
    @sales = @product.sales.where(status_id: Sale::REJECTED).order(:status_id)
  end

	def analysis_sources_type_report
    @sales = @product.sales
    @buyers = []
    @sales.each do |sale|
      @buyers << sale.buyer
    end
		name = []
    number = []
    result = []
    @buyers.each do |p|
      name << p.sources_type.try(:name)
      number << p.sources_type.try(:name).to_s
    end

    name.uniq.each do |t|
      result << name.count { |x| x == t }
    end
    @combine = Hash[name.uniq.zip result]
    # render :text => @combine
    # render :text => name.uniq
    # render :text => number
    # render :text => result
    # render :text => name.count { |x| x == "newspaper" }
  end

  def analysis_region_report
    @sales = @product.sales
    @buyers = []
    @sales.each do |sale|
      @buyers << sale.buyer
    end
    name = []
    number = []
    result = []
    @buyers.each do |p|
      name << p.region.try(:name)
      number << p.region.try(:name).to_s
    end

    name.uniq.each do |t|
       result << name.count { |x| x == t }
    end
    @combine = Hash[name.uniq.zip result]
  end

  def sales
    @today_sales = Sale.where("DATE(confirm_date) = ? and status_id = ?", Date.current, Sale::COMPLETED)
    @yesterday_sales = Sale.where("DATE(confirm_date) = ? and status_id = ?", (Date.current - 1.day), Sale::COMPLETED)

    # this week sales
    weeks_array = Date.current.week_split
    weeks_array.each do |week|
      @this_week = week if week.include?(Date.current.day)
    end
    if @this_week.first.nil?
      first_day = "01"
    else
      first_day = @this_week.first
    end
    if @this_week.last.nil?
      last_day = Date.current.end_of_month
    else
      last_day = @this_week.last
    end
    to_day = Date.current
    # this week sales
    @this_week_sales = Sale.where(confirm_date: "#{to_day.year}-#{to_day.month}-#{first_day}".to_date.."#{to_day.year}-#{to_day.month}-#{last_day}".to_date, status_id: Sale::COMPLETED)

    # this month sales
    @this_month_sales = Sale.where(confirm_date: Date.current.beginning_of_month..Date.current.end_of_month, status_id: Sale::COMPLETED)

    # this quarter sales
    @this_quarter_sales = Sale.where(confirm_date: Date.current.beginning_of_quarter..Date.current.end_of_quarter, status_id: Sale::COMPLETED)

    # this year sales
    @this_year_sales = Sale.where(confirm_date: Date.current.beginning_of_year..Date.current.end_of_year, status_id: Sale::COMPLETED)
  end

  def monthly_sales
    jan = "#{Date.current.year}-01-01".to_date
    feb = "#{Date.current.year}-02-01".to_date
    mar = "#{Date.current.year}-03-01".to_date
    apr = "#{Date.current.year}-04-01".to_date
    may = "#{Date.current.year}-05-01".to_date
    jun = "#{Date.current.year}-06-01".to_date
    jul = "#{Date.current.year}-07-01".to_date
    ogo = "#{Date.current.year}-08-01".to_date
    sep = "#{Date.current.year}-09-01".to_date
    oct = "#{Date.current.year}-10-01".to_date
    nov = "#{Date.current.year}-11-01".to_date
    dec = "#{Date.current.year}-12-01".to_date
    @jan_sales = Sale.where(confirm_date: jan.beginning_of_month..jan.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    @feb_sales = Sale.where(confirm_date: feb.beginning_of_month..feb.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    @mar_sales = Sale.where(confirm_date: mar.beginning_of_month..mar.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    @apr_sales = Sale.where(confirm_date: apr.beginning_of_month..apr.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    @may_sales = Sale.where(confirm_date: may.beginning_of_month..may.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    @jun_sales = Sale.where(confirm_date: jun.beginning_of_month..jun.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    @jul_sales = Sale.where(confirm_date: jul.beginning_of_month..jul.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    @ogo_sales = Sale.where(confirm_date: ogo.beginning_of_month..ogo.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    @sep_sales = Sale.where(confirm_date: sep.beginning_of_month..sep.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    @oct_sales = Sale.where(confirm_date: oct.beginning_of_month..oct.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    @nov_sales = Sale.where(confirm_date: nov.beginning_of_month..nov.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    @dec_sales = Sale.where(confirm_date: dec.beginning_of_month..dec.end_of_month, status_id: Sale::COMPLETED, product_id: @product.id)
    
  end

  def agency_sales
    if is_top_level_management?
      agencies = current_user.company.agencies.order(:name)
      @result = []
      @pie_chart_data = []
      current_company = current_user.company
      sales = Sale.where("user_id IN(?) and status_id = ? and product_id = ?", current_company.user_ids, Sale::COMPLETED, @product.id)
      @result << [current_company, sales]
      total = sales.inject(0) do |sum, sale|
        sum += sale.actual_price
      end
      @pie_chart_data << [current_company.name, total]

      agencies.each do |agency|
        sales = Sale.where("user_id IN(?) and status_id = ? and product_id = ?", agency.user_ids, Sale::COMPLETED, @product.id)
        @result << [agency, sales]
        total = sales.inject(0) do |sum, sale|
          sum += sale.actual_price
        end
        @pie_chart_data << [agency.name, total]
      end
    else
      flash[:alert] = "Sorry, you don't have access right."
      redirect_to :back
    end
  end
  
  # ============ excel ===============

  def export_sources_type_excel
    @sales = @product.sales
    @buyers = []
    @sales.each do |sale|
      @buyers << sale.buyer
    end
    sources_name = []
    result = []
    @buyers.each do |p|
      sources_name << p.sources_type.try(:name)
    end

    sources_name.uniq.each do |t|
      result << sources_name.count { |x| x == t }
    end
    @source_combine = Hash[sources_name.uniq.zip result]
    respond_to do |format|
      format.csv { render text: @source_combine.to_csv }
      format.xls
    end
  end

  def export_regions_excel
    @sales = @product.sales
    @buyers = []
    @sales.each do |sale|
      @buyers << sale.buyer
    end
        name = []
        number = []
        result = []
        @buyers.each do |p|
          name << p.region.try(:name)
          number << p.region.try(:name).to_s
        end

        name.uniq.each do |t|
           result << name.count { |x| x == t }
        end
        @region_combine = Hash[name.uniq.zip result]

    respond_to do |format|
      format.csv { render text: @region_combine.to_csv }
      format.xls
    end
  end

  def export_analysis_age_race_excel
    @sales = @product.sales
    @buyers = []
    @sales.each do |sale|
      @buyers << sale.buyer
    end
    respond_to do |format|
      format.csv { render text: @buyers.to_csv }
      format.xls
    end
  end

  def export_summary_report_excel
    @sales = @product.sales
    respond_to do |format|
      format.csv { render text: @sales.to_csv }
      format.xls
    end
  end

  private

  def find_product
    @product = Product.friendly.find params[:id]
  end


end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_all_order.html.erb
 <div id="all_order-tab" class="tab-pane fade active in">        
      <div class="table-responsive">
      <%#= render :text => Buyer.first.to_json %>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Date</th>
              <th>Agency</th>
              <th>Agent</th>
              <th>Purchaser</th>
              <th>Contact Number</th>
              <th>Price</th>
              <th>Type</th>
              <th>Lot</th>
              <th>Age</th>
              <th>Race</th>
              <th>Region</th>
              <th>Source</th>
              <th>Remark</th>
            </tr>
          </thead>
          
          <tbody>
            <% @sales.order("id ASC").each do |p| %>
            <tr>
              <td><%= p.created_at.strftime("%d-%m-%Y") rescue "" %></td>
              <td><%= p.user.company.try(:name) %></td>
              <td><%= p.user.try(:username) %></td>
              <td><%= p.buyer.try(:full_name) %></td>
              <td><%= p.buyer.try(:mobile_contact_number) %></td>
              <td>
                <% lot = p.lot %>
                <%= number_with_delimiter(p.actual_price) %>
     
              </td>
              <td><%= ProductType.find_by_id(p.product_id).try(:name) %></td>
              <td><%= lot.name %></td>
              <td>
                <% if p.buyer.try(:age) == 1 %>
                  18-30
                  <% elsif p.buyer.try(:age) == 2 %>
                  31-40
                  <% elsif p.buyer.try(:age) == 3 %>
                  41-50
                  <% elsif p.buyer.try(:age) == 4 %>
                  51-60
                  <% elsif p.buyer.try(:age) == 5 %>
                  60 & above
                  <% else %>
                  <% end %>
              </td>
              <td>
                <% if p.buyer.try(:race) == 1 %>
                  Chinese
                <% elsif p.buyer.try(:race) == 2 %>
                  Melayu
                <% elsif p.buyer.try(:race) == 3 %>
                  Indian
                <% elsif p.buyer.try(:race) == 4 %>
                  Other
                <% else %>
                <% end %>
              </td>
              <td><%= p.buyer.region.try(:name) %></td>
              <td><%= p.buyer.sources_type.try(:name) %></td>
              <td>
                <% if p.status_id == Sale::PENDING %>
                  Pending
                <% elsif p.status_id == Sale::COMPLETED %>
                 Completed
                <% elsif p.status_id == Sale::REJECTED %>
                 Rejected : <%= p.reject_reason %>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
          
        </table>
      </div>
    </div>
        

app/views/reports/_completed_order.html.erb
<div id="completed_order-tab" class="tab-pane fade ">

  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Date</th>
          <th>SPA</th>
          <th>Agency</th>
          <th>Agent</th>
          <th>Purchaser</th>
          <th>Contact Number</th>
          <th>Price</th>
          <th>Type</th>
          <th>Lot</th>
          <th>Age</th>
          <th>Race</th>
          <th>Region</th>
          <th>Source</th>
          <th>Remark</th>
        </tr>
      </thead>
      
      <tbody>
        <% @sales.where("status_id = 2").each do |p| %>
        <tr>
          <td><%= p.created_at.strftime("%d-%m-%Y") rescue "" %></td>
          <td><%= p.confirm_date.strftime("%d-%m-%Y") rescue "" %></td>
          <td><%= p.user.company.try(:name) %></td>
          <td><%= p.user.try(:username) %></td>
          <td><%= p.buyer.try(:full_name) %></td>
          <td><%= p.buyer.try(:mobile_contact_number) %></td>
          <td><%= number_with_delimiter(p.actual_price) %></td>
          <td><%= ProductType.find_by_id(p.product_id).try(:name) %></td>
          <td><%= p.lot.try(:name) %></td>
          <td>
            <% if p.buyer.age == 1 %>
              18-30
              <% elsif p.buyer.age == 2 %>
              31-40
              <% elsif p.buyer.age == 3 %>
              41-50
              <% elsif p.buyer.age == 4 %>
              51-60
              <% elsif p.buyer.age == 5 %>
              60 & above
              <% else %>
              <% end %>
          </td>
          <td>
            <% if p.buyer.race == 1 %>
              Chinese
            <% elsif p.buyer.race == 2 %>
              Melayu
            <% elsif p.buyer.race == 3 %>
              Indian
            <% elsif p.buyer.race == 4 %>
              Other
            <% else %>
            <% end %>
          </td>
          <td><%= p.buyer.region.try(:name) %></td>
          <td><%= p.buyer.sources_type.try(:name) %></td>
          <td>
            Completed
          </td>
        </tr>
        <% end %>
      </tbody>
      
    </table>    
  </div>
</div>
        

app/views/reports/agency_sales.html.erb
      <div id="agency_sales_pie_chart" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto">
      </div>

      <hr> 
    <div class="table-responsive">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th class="text-center">Agency</th>
            <th class="text-center">Unit</th>
            <th class="text-center">Sales</th>
          </tr>
          <% @result.each do |sale_array| %>
          <% agency_sales = sale_array.last %>
          <% 
            total = agency_sales.inject(0) do |sum, sale|  
          	  sum += sale.actual_price
            end
          %>
          <tr>
            <td><%= sale_array.first.name %></td>
            <td class="text-center"><%= agency_sales.count %></td>
            <td class="text-center">RM <%= number_with_delimiter(total) %></td>
          </tr>
          <% end %>
        </tbody>
        
      </table>
      <%#= link_to "Export Excel", export_sources_type_excel_reports_path(format: "xls"), :class=>"btn btn-primary" %>
    </div>


<%= render "/layouts/highchart_options"  %>

<script type="text/javascript">
  $(function () {
  	 var agency_sales = [];
     <% @pie_chart_data.each do |data_array| %>
       agency_sales.push(["<%= data_array.first %>", <%= data_array.last %>]);
     <% end %>
 
            $('#agency_sales_pie_chart').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: 1,//null,
                    plotShadow: false
                },
                title: {
                    text: 'Agency Sales Report.'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.0f} %</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.percentage:.0f} %',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        }
                    }
                  },
                series: [{
                    type: 'pie',
                    name: 'Unit Percentage',
                    data: agency_sales
                    
                }]
            });

   $("div.highcharts-container svg text:last").html("");
          });


</script>     

app/views/reports/analysis_age_report.html.erb
        

        <div id="age_pie_chart" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
      
      <hr> 
      <div class="table-responsive">
        <table class="table table-bordered">
          <tbody>
            <tr>
              <th>Age</th>
              <th>Pax</th>
            </tr>
            <tr>
              <td>18-30</td>
              <td><%= a = @buyers.select {|buyer| buyer.age == 1}.size %></td>
            </tr>
            <tr>
              <td>31-40</td>
              <td><%= b = @buyers.select {|buyer| buyer.age == 2}.size %></td>
            </tr>
            <tr>
              <td>41-50</td>
              <td><%= c = @buyers.select {|buyer| buyer.age == 3}.size %></td>
            </tr>
            <tr>
              <td>51-60</td>
              <td><%= d = @buyers.select {|buyer| buyer.age == 4}.size %></td>
            </tr>
            <tr>
              <td>60 & above</td>
              <td><%= e = @buyers.select {|buyer| buyer.age == 5}.size %></td>
            </tr>
          </tbody>
          
        </table>

         <%= link_to "Export to Excel", export_analysis_age_race_excel_report_path(@product, format: "xls"), :class=>"btn btn-primary" %>
      </div>


  <%= render "/layouts/highchart_options"  %>

<script type="text/javascript">
  $(function () {

            var a = <%= a %>
            var b = <%= b %>
            var c = <%= c %>
            var d = <%= d %>
            var e = <%= e %>
            var age_unit_cart = [["18-30", a],["31-40", b],["41-50", c],["51-60", d],["60 & above", e]];
            $('#age_pie_chart').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: 1,//null,
                    plotShadow: false
                },
                title: {
                    text: 'Summary Ages Report.'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.0f} %</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.percentage:.0f} %',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        }
                    }
                  },
                series: [{
                    type: 'pie',
                    name: 'Unit Percentage',
                    data: age_unit_cart
                          // arrayMy
                        // ['Firefox',   40.0],
                        // ['IE',       20.0],
                        // // {
                        // //     name: 'Chrome',
                        // //     y: 12.8,
                        // //     sliced: true,
                        // //     selected: true
                        // // }, 
                }]
            });
    $("div.highcharts-container svg text:last").html("");
          });

</script>     

app/views/reports/analysis_race_report.html.erb
  
        <div id="race_pie_chart" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
      
      <hr> 
      <div class="table-responsive">
        <table class="table table-bordered">
          <tbody>
            <tr>
              <th>Type</th>
              <th>Race</th>
            </tr>
            <tr>
              <td>chinese</td>
              <td><%= chinese = @buyers.select {|buyer| buyer.race == 1}.size %></td>
            </tr>
            <tr>
              <td>bumiputera</td>
              <td><%= bumiputera = @buyers.select {|buyer| buyer.race == 2}.size %></td>
            </tr>
            <tr>
              <td>indian</td>
              <td><%= indian = @buyers.select {|buyer| buyer.race == 3}.size %></td>
            </tr>
            <tr>
              <td>others</td>
              <td><%= others = @buyers.select {|buyer| buyer.race == 4}.size %></td>
            </tr>
            
          </tbody>
          
        </table>
        <%= link_to "Export to Excel", export_analysis_age_race_excel_report_path(@product, format: "xls"), :class=>"btn btn-primary" %>
      </div>


<%= render "/layouts/highchart_options"  %>

<script type="text/javascript">
  $(function () {

            // var combine = <%#= raw sold.to_json %>
            var chinese = <%= chinese %>
            var bumiputera = <%= bumiputera %>
            var indian = <%= indian %>
            var others = <%= others %>
            // console.log(sold, reserved, available);


            var race_unit_cart = [["chinese", chinese],["bumiputera", bumiputera],["indian", indian],["others", others]];
            $('#race_pie_chart').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: 1,//null,
                    plotShadow: false
                },
                title: {
                    text: 'Analysis Race Report.'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.0f} %</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.percentage:.0f} %',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        }
                    }
                  },
                series: [{
                    type: 'pie',
                    name: 'Unit Percentage',
                    data: race_unit_cart
                          // arrayMy
                        // ['Firefox',   40.0],
                        // ['IE',       20.0],
                        // // {
                        // //     name: 'Chrome',
                        // //     y: 12.8,
                        // //     sliced: true,
                        // //     selected: true
                        // // }, 
                }]
            });
   $("div.highcharts-container svg text:last").html("");
          });

</script>     

app/views/reports/analysis_region_report.html.erb
      <div id="unit_region_chart" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
    
    <hr> 
    <div class="table-responsive">
    <%#= render :text => Buyer.first.to_json %>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th>Region</th>
            <th>Unit</th>
          </tr>
          <% @combine.each do |key, value| %>
            <% if key %>
            <tr>
              <td class="text-center"><%= key %></td>
              <td><%= value %></td>
            </tr>
            <% else %>
            <% end %>
          <% end %>
        </tbody>
        
      </table>
      <%= link_to "Export to Excel", export_regions_excel_report_path(@product, format: "xls"), :class=>"btn btn-primary" %>
    </div>


<%= render "/layouts/highchart_options"  %>

<script type="text/javascript">
  $(function () {
            var combine = <%= raw @combine.to_json %>
            console.log(combine);

            var f = [];
            $.each( combine, function( key, value ) {
              // arrayMy.push("'" + key + "'" + ", " + value);
              var x = new Array(key , value);
              f.push(x);
            });
            console.log(f);

            $('#unit_region_chart').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: 1,//null,
                    plotShadow: false
                },
                title: {
                    text: 'Analysis Region Report.'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.0f} %</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.percentage:.0f} %',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        }
                    }
                  },
                series: [{
                    type: 'pie',
                    name: 'Unit Percentage:',
                    data: f
                          // arrayMy
                        // ['Firefox',   40.0],
                        // ['IE',       20.0],
                        // // {
                        // //     name: 'Chrome',
                        // //     y: 12.8,
                        // //     sliced: true,
                        // //     selected: true
                        // // }, 
                }]
            });
   $("div.highcharts-container svg text:last").html("");
          });

</script>

app/views/reports/export_regions_excel.xls.erb
<table class="table table-bordered">
        <tbody>
          <tr>
            <th>Region</th>
            <th>Unit</th>
          </tr>
             <% @region_combine.each do |key, value| %>
          <tr>
            <td class="text-center"><%= key %></td>
            <td><%= value %></td>
          </tr>
          <% end %>
        </tbody>        
</table>

app/views/reports/summary_report.html.erb
  <div class="tab-base">
          
        <!--Nav Tabs-->
        <ul class="nav nav-tabs">
          <li class="active">
            <a data-toggle="tab" href="#all_order-tab">All Sales</a>
          </li>
          <li>
            <a data-toggle="tab" href="#completed_order-tab">Completed Sales</a>
          </li>
          <!-- <li>
            <a data-toggle="tab" href="#rejected_order-tab">Rejected Sales</a>
          </li> -->
        </ul>

        <!--Tabs Content-->
        <div class="tab-content">
            <%= render "/reports/all_order" %>
            <%= render "/reports/completed_order" %>
            <%#= render "/reports/rejected_order" %>
        </div>
        <%= link_to "Export to Excel", export_summary_report_excel_report_path(@product, format: "xls"), :class=>"btn btn-primary" %>
  </div>